### PR TITLE
[docker] No need to restart sshd

### LINKED ISSUE #611: Beaker 2.1.0 fails on creation of Docker containers with RHEL6 image
Since upgrading to Beaker 2.1.0 I have been unable to successfully provision Docker containers using a Redhat 6 docker image.

It looks like it fails when trying to restart the sshd service.

```
beaker::Hypervisor, found some docker boxes to create
Provisioning docker
provisioning beaker4
Creating image
Dockerfile is         FROM vrtstdkr001:8080/lightfa/beaker
          RUN yum clean all
          RUN yum install -y sudo openssh-server openssh-clients curl ntpdate
          RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key
          RUN ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key
        RUN mkdir -p /var/run/sshd
        RUN echo root:root | chpasswd
        EXPOSE 22
        CMD /usr/sbin/sshd -D
post
/v1.12/build
{:rm=>true}
Dockerfile0000640000000000000000000000061300000000000013245 0ustar00wheelwheel00000000000000        FROM vrtstdkr001:8080/lightfa/beaker
          RUN yum clean all
          RUN yum install -y sudo openssh-server openssh-clients curl ntpdate
          RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key
          RUN ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key
        RUN mkdir -p /var/run/sshd
        RUN echo root:root | chpasswd
        EXPOSE 22
        CMD /usr/sbin/sshd -D

Creating container from image 137049ceb16c
post
/v1.12/containers/create
{}
{"Image":"137049ceb16c","Hostname":"beaker4"}
Starting container cc75e9c3e4a56ae509f15144f32a075dc160634b66782fbd5fe3f3ed65380a25
post
/v1.12/containers/cc75e9c3e4a56ae509f15144f32a075dc160634b66782fbd5fe3f3ed65380a25/start
{}
{"PublishAllPorts":true,"Privileged":true}
get
/v1.12/containers/cc75e9c3e4a56ae509f15144f32a075dc160634b66782fbd5fe3f3ed65380a25/json
{}

get
/v1.12/containers/cc75e9c3e4a56ae509f15144f32a075dc160634b66782fbd5fe3f3ed65380a25/json
{}

node available as  ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@0.0.0.0 -p 49233

beaker4 10:23:57$ rpm -q curl
Created ssh connection to 0.0.0.0, user: root, opts: {:password=>"root", :port=>"49233", :forward_agent=>false, :user=>"root"}
curl-7.19.7-37.el6_5.3.x86_64

beaker4 executed in 0.20 seconds

beaker4 10:23:57$ rpm -q ntpdate
ntpdate-4.2.6p5-1.el6.x86_64

beaker4 executed in 0.02 seconds

beaker4. 10:23:57$ echo "/usr/bin"
/usr/bin

beaker4 executed in 0.01 seconds

beaker4 10:23:57$ echo "/opt/puppet-git-repos/hiera/bin"
/opt/puppet-git-repos/hiera/bin

beaker4  executed in 0.01 seconds

beaker4 10:23:57$ echo "/opt/puppet-git-repos/hiera/lib"
/opt/puppet-git-repos/hiera/lib

beaker4 executed in 0.01 seconds

beaker4 10:23:57$ echo "/opt/puppet-git-repos/hiera-puppet/lib"
/opt/puppet-git-repos/hiera-puppet/lib

beaker4 executed in 0.01 seconds
setting local environment on beaker4

beaker4 10:23:57$ echo '
PermitUserEnvironment yes' >> /etc/ssh/sshd_config

beaker4 executed in 0.01 seconds

beaker4  10:23:57$ /sbin/service sshd restart
Stopping sshd: /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/ruby_compat.rb:30:in `select': closed stream (IOError)
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/ruby_compat.rb:30:in `io_select'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/transport/packet_stream.rb:73:in `available_for_read?'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/transport/packet_stream.rb:85:in `next_packet'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:178:in `block in poll_message'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:173:in `loop'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:173:in `poll_message'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:460:in `dispatch_incoming_packets'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:221:in `preprocess'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:205:in `process'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `block in loop'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
        from /usr/local/lib/ruby/gems/2.0.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/ssh_connection.rb:96:in `try_to_execute'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/ssh_connection.rb:107:in `execute'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/host.rb:271:in `block in exec'
        from /usr/local/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/host.rb:270:in `exec'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/host_prebuilt_steps.rb:489:in `block in set_env'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/shared/host_manager.rb:74:in `run_block_on'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/shared/host_manager.rb:71:in `block in run_block_on'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/shared/host_manager.rb:70:in `map'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/shared/host_manager.rb:70:in `run_block_on'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/dsl/patterns.rb:32:in `block_on'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/host_prebuilt_steps.rb:471:in `set_env'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/hypervisor.rb:111:in `configure'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/network_manager.rb:71:in `block in configure'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/network_manager.rb:70:in `each_key'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/network_manager.rb:70:in `configure'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-rspec-4.0.0/lib/beaker-rspec/beaker_shim.rb:43:in `configure'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-rspec-4.0.0/lib/beaker-rspec/spec_helper.rb:42:in `block in <top (required)>'
        from /usr/local/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.7/lib/rspec/core.rb:120:in `configure'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-rspec-4.0.0/lib/beaker-rspec/spec_helper.rb:5:in `<top (required)>'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-rspec-4.0.0/lib/beaker-rspec.rb:5:in `<module:BeakerRSpec>'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-rspec-4.0.0/lib/beaker-rspec.rb:1:in `<top (required)>'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:110:in `require'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:110:in `rescue in require'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:35:in `require'
        from /etc/puppet/environments/dev/modules/varnish/spec/spec_helper_acceptance.rb:2:in `<top (required)>'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
        from /usr/local/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/cli.rb:44:in `block in initialize'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/cli.rb:43:in `each'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/cli.rb:43:in `initialize'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/bin/beaker:6:in `new'
        from /usr/local/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/bin/beaker:6:in `<top (required)>'
        from /usr/local/bin/beaker:23:in `load'
        from /usr/local/bin/beaker:23:in `<main>'
``

If I comment out line 132 of beaker/hypervisor.rb 
i.e. # set_env(@hosts, @options)

Then it will successfully provision the Docker container, but it doesn't find any tests to run.

The command I am using to run the tests is
beaker --log-level trace  --hosts spec/acceptance/nodesets/default.yml --helper /etc/puppet/environments/dev/modules/varnish/spec/spec_helper_acceptance.rb --tests /etc/puppet/environments/dev/modules/varnish/spec/acceptance/standard_spec.rb

The host yaml file is as follows

```yaml
HOSTS:
  beaker4:
    roles:
      - master
      - agent
    platform: el-6-x86_64
    image:  vrtstdkr001:8080/lightfa/beaker
    hypervisor: docker
    docker_preserve_image: false
CONFIG:
  type: foss
  log_level: verbose
```

It looks like restarting the ssh service closes the connection to the image and this causes the process to fail? I am missing something?

Thanks
Andy

### PR DESCRIPTION
**Pull request by carlossg**
Do not restart the sshd service when using Docker as it causes the container to stop.
Fix #611

### CODE REVIEW

**Comment by carlossg** [comment]
I think it fixes #567 too

By default docker container is running sshd as the main process (unless overriden with `docker_cmd` option), and when beaker executes the ssh restart the process is killed and the container is stopped/killed too as it was the main process

**Comment by electrical** [comment]
As i mentioned on IRC i personally don't like this solution as it completely disables it for any docker image.
Since i launch the /sbin/init process the current workflow does work for me so i think better detection is in order or make it configurable in the host config.

**Comment by carlossg** [comment]
If you are using a custom CMD maybe you should be responsible to customize your sshd config and not let beaker mess with your config files?

Right now the default CMD is failing, there are other options like change the CMD to `service ssh start; tail -f /dev/null`

**Comment by electrical** [comment]
An option could be called `docker_setup_env` defaulting to false so that the default CMD doesn't fail and let other people who customized the docker_cmd set the docker_setup_env to true?

as a side note, the defaults in this case for the docker hypervisor won't allow you to do tests around the service managers so any calls for service type of puppet fill fail.

File: lib/beaker/hypervisor/docker.rb [hunk 1]
```diff
@@ -4,6 +4,7 @@ class Docker < Beaker::Hypervisor
     def initialize(hosts, options)
       require 'docker'
       @options = options
+      @options[:set_env] = false
```
Comment (anodelman) [inline lib/beaker/hypervisor/docker.rb]: I'm not a big fan of this sort of hidden override (ie, we'll listen to your option, unless you run docker and then we'll ignore you).  Any reason why you can't just override with your desired set_env value in your host configuration file?

Comment (carlossg) [inline lib/beaker/hypervisor/docker.rb]: I'm open to suggestions, but set_env should default to false in docker environments. You can't have a default of

* run sshd as main process, and
* restart sshd

because it just doesn't work, and it's an issue for new users.
I see it more as sent_env defaults to false for Docker and you can override it if you want, because you need to use a custom image or command too

Comment (anodelman) [inline lib/beaker/hypervisor/docker.rb]: In that case, the docker hypervisor should overwrite the whole 'configure' method to one that is more appropriate - instead of picking and choosing out of the default configure method.

**Comment by anodelman** [comment]
Also, if we do not run the set_env section of the configure method then the PATH and RUBYPATH will not be correctly set and you will not be able to run puppet commends.

**Comment by carlossg** [comment]
Let's see if this updated solution works for everybody

**Comment by mcanevet** [comment]
This PR works for me.

**Comment by cassianoleal** [comment]
:+1: Works for me too!

**Comment by anodelman** [comment]
So, by default the set_env gets called for docker now.  In what case do you not want to set the env?  I think that additional documentation/yard doc-ing would really help define the two workflows that you are creating.

**Comment by carlossg** [comment]
I'm not changing the existing workflow, just the CMD executed. 

I just happened to left there the ability to override set_env if anyone needs to

**Comment by anodelman** [comment]
This looks fine to me.  @electrical, +1 from you?

**Comment by anodelman** [comment]
Final nit - please associate your commit with a github issue number (gh-xxx).

**Comment by carlossg** [comment]
done

**Comment by anodelman** [comment]
ok to test

**Comment by anodelman** [comment]
Failures unrelated to patch.
